version: "3"
services:
  bigthingdb:
    image: postgres:11.5
    volumes:
      - ./pg-data:/var/lib/postgres/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: bigdb
    volumes:
      - pg-data